name: domain
description: A Flutter package to contain the domain layer.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
flutter:  
  uses-material-design: true