name: remote
description: A Flutter package to contain remote related logic.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data/
  dio: ^4.0.6
  injectable: ^1.5.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  retrofit: ^3.0.1+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  retrofit_generator: ^4.1.1
flutter:
  uses-material-design: true